title: My First Website (Marc Seemann)
description: Experimenting with GitHub Pages and Jekyll
remote_theme: pages-themes/cayman
markdown: kramdown

plugins:
  - jekyll-remote-theme

sass:
  style: compressed
